name: "[./.github/workflows/travis-packaging-macos-test.yaml]"

on:
  workflow_call:

jobs:
  macos-test-installer:
    # https://earthly.dev/blog/creating-and-hosting-your-own-deb-packages-and-apt-repo/#step-1-creating-a-deb-package
    runs-on: macos-latest
    steps:
      # Get Linux deb archive
      - uses: actions/download-artifact@v3
        with:
          name: gama-mac-signed

      - name: Test Gama w/ JDK
        run: |
          hdiutil attach ./gama.application-macosx.cocoa.x86_64_withJDK.dmg
          cp -r /Volumes/Gama/Gama.app ~/
          bash ~/Gama.app/Contents/headless/gama-headless.sh -help
          rm -fr ~/Gama.app
          hdiutil detach /Volumes/Gama
      
      - name: Set up Adopt OpenJDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          java-package: jdk

      - name: Test Gama w/o JDK
        run: |
          hdiutil attach ./gama.application-macosx.cocoa.x86_64.dmg
          cp -r /Volumes/Gama/Gama.app ~/
          bash ~/Gama.app/Contents/headless/gama-headless.sh -help
          hdiutil detach /Volumes/Gama