name: "[./.github/workflows/travis-build-test.yaml]"

on:
  workflow_call:
    inputs:
      artifact_download_id: 
        required: false
        default: "gama-compiled-archive" 
        type: string

jobs:
  compilation: 
    runs-on: ubuntu-latest
    steps:
      - name: Get linux testing releases
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_download_id }}

      - name: Extract GAMA w/o JDK
        run: tar xvf $GITHUB_WORKSPACE/gama.application-linux.gtk.x86_64.tar.gz

      - name: Set up Adopt OpenJDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          java-package: jdk

      - name: Test release
        run: |
          bash $GITHUB_WORKSPACE/headless/gama-headless.sh -m 10g -validate && \
          bash $GITHUB_WORKSPACE/headless/gama-headless.sh -m 10g -test && \
          echo "All good ! ðŸŽ‰"
